"""add soft to jd_skill_type_enum

Revision ID: 19c9c2308873
Revises: 5da7109026e0
Create Date: 2026-04-20 11:00:14.556093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c9c2308873'
down_revision = '5da7109026e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # MySQL requires raw SQL for enum modifications
    op.execute("ALTER TABLE jd_skills MODIFY skill_type ENUM('primary', 'secondary', 'soft') NOT NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE jd_skills MODIFY skill_type ENUM('primary', 'secondary') NOT NULL")
    # ### end Alembic commands ###
