"""add job_code to job_descriptions

Revision ID: 5da7109026e0
Revises: c3f9f0a9f2b1
Create Date: 2026-04-20 10:44:45.741593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da7109026e0'
down_revision = 'c3f9f0a9f2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_code', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_descriptions_job_code'), ['job_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_descriptions_job_code'))
        batch_op.drop_column('job_code')

    # ### end Alembic commands ###
