"""add calibration_url and rate_scale columns to job_descriptions

Revision ID: 8f1g2h3i4j5k
Revises: 19c9c2308873
Create Date: 2026-04-22 10:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1g2h3i4j5k'
down_revision = '19c9c2308873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('calibration_url', sa.String(500), nullable=True))
    op.add_column('job_descriptions', sa.Column('rate_scale', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'rate_scale')
    op.drop_column('job_descriptions', 'calibration_url')
    # ### end Alembic commands ###
