"""add jd_recruiter_assignments table

Revision ID: d4e7f1a2b3c4
Revises: 8f1g2h3i4j5k
Create Date: 2026-04-22 10:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e7f1a2b3c4'
down_revision = '8f1g2h3i4j5k'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jd_recruiter_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jd_id', 'recruiter_id', name='uq_jd_recruiter')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jd_recruiter_assignments')
    # ### end Alembic commands ###
